//=========================
// Next.js App Router ルートレイアウト
//=========================
// このファイルは、アプリケーション全体の共通レイアウトを定義します。
// 以下の機能がすべてのページ（/simple を含む）に適用されます：
//
// 1. HTML構造: <html> と <body> タグを提供
// 2. フォント設定: Noto Sans JP フォントを適用
// 3. メタデータ: title, description を設定
// 4. スタイル: アンチエイリアス効果を適用
//
// 影響範囲: /, /simple, その他すべてのページ
//=========================

import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover"
        />
      </head>
      <body className={`${notoSansJP.className} antialiased`}>{children}</body>
    </html>
  );
}
